import React from 'react';
import { motion } from 'motion/react';
import { Brain, ShieldCheck, LayoutDashboard, GitBranch, FlaskConical } from 'lucide-react';

const FEATURES = [
  {
    title: "AI Urgency Classification",
    description: "Submit your symptoms and receive an urgency level — Emergency, High, Medium, or Low — generated by a language model in real time.",
    icon: Brain,
    className: "lg:col-span-2 lg:row-span-2 bg-primary text-white",
    iconColor: "text-white",
  },
  {
    title: "Secure Authentication",
    description: "JWT-based auth with bcrypt password hashing keeps your data protected.",
    icon: ShieldCheck,
    className: "bg-surface-container-low text-on-surface",
    iconColor: "text-primary",
  },
  {
    title: "Personal Dashboard",
    description: "View all your past submissions, urgency ratings, and AI explanations in one place.",
    icon: LayoutDashboard,
    className: "bg-surface-container-low text-on-surface",
    iconColor: "text-tertiary",
  },
  {
    title: "MERN Stack",
    description: "Built with MongoDB, Express, React, and Node.js for a modern full-stack architecture.",
    icon: GitBranch,
    className: "bg-surface-container-low text-on-surface",
    iconColor: "text-secondary",
  },
  {
    title: "Research-Driven",
    description: "A case study evaluating where AI classification performs well and where it falls short.",
    icon: FlaskConical,
    className: "bg-surface-container-low text-on-surface",
    iconColor: "text-primary",
  },
];

export const Features = () => {
  return (
    <section id="how-it-works" className="py-24 px-6 md:px-12 bg-surface">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-4xl md:text-5xl font-headline font-extrabold text-on-surface leading-tight"
          >
            How HealthHive <br />
            <span className="text-editorial-gradient">Works.</span>
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="text-on-surface-variant mt-4 max-w-xl mx-auto"
          >
            A full-stack research platform exploring AI-assisted symptom triage.
          </motion.p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 auto-rows-[240px]">
          {FEATURES.map((card, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, scale: 0.95 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.1 }}
              className={`p-8 rounded-3xl flex flex-col justify-between ambient-shadow group hover:-translate-y-1 transition-all duration-300 ${card.className}`}
            >
              <div className={`w-12 h-12 rounded-2xl flex items-center justify-center mb-6 ${card.className.includes('bg-primary') ? 'bg-white/20' : 'bg-white'}`}>
                <card.icon className={`w-6 h-6 ${card.iconColor}`} />
              </div>
              <div>
                <h3 className="text-xl font-headline font-bold mb-3">{card.title}</h3>
                <p className={`text-sm leading-relaxed ${card.className.includes('bg-primary') ? 'text-white/80' : 'text-on-surface-variant'}`}>
                  {card.description}
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};